arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
endOfLine: "lf"
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
quoteProps: "as-needed"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "es5"
useTabs: false
